---
AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Description: An Elasticache AuthToken rotator.

Metadata:
  AWS::ServerlessRepo::Application:
    Name: elasticache-auth-token-rotator
    Description: >-
      A Secrets Manager rotation Lambda Function which can rotate the auth token
      for ElastiCache replication groups, along with a secret target attachement
      Lambda Function for use as a CloudFormation custom resource.
    Author: Christopher Osborn
    SpdxLicenseId: Apache-2.0
    LicenseUrl: ./LICENSE
    ReadmeUrl: ./README.md
    Labels:
    - cimpress
    - caching
    - redis
    - elasticache
    - replication-group
    - rotate
    - rotation
    - rotator
    - auth-token
    HomePageUrl: https://github.com/Cimpress-MCP/ElastiCache-Auth-Token-Rotator
    SemanticVersion: 2.0.0
    SourceCodeUrl: https://github.com/Cimpress-MCP/ElastiCache-Auth-Token-Rotator

Parameters:
  Endpoint:
    Type: String
    Description: The Secrets Manager endpoint to hit.
  FunctionName:
    Type: String
    Description: The name of the Lambda Function.
  InvokingServicePrincipal:
    Type: String
    Description: The service principal of the invoking service.
    Default: secretsmanager.amazonaws.com
  KmsKeyArn:
    Type: String
    Description: The KMS key used to encrypt the secret being rotated.
    Default: ''
  VpcSubnetIds:
    Type: CommaDelimitedList
    Description: A list of VPC subnet IDs.
  VpcSecurityGroupIds:
    Type: CommaDelimitedList
    Description: A list of VPC security group IDs.

Conditions:
  KmsKeyArnExists: !Not [ !Equals [ '', !Ref KmsKeyArn ] ]

Globals:
  Function:
    Runtime: python3.8
    Environment:
      Variables:
        SECRETS_MANAGER_ENDPOINT: !Ref Endpoint

Resources:
  SecretDecryptionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: KmsKeyArnExists
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action: kms:DescribeKey
          Resource: !Ref KmsKeyArn
          Condition:
            StringEquals:
              kms:ViaService: !Sub secretsmanager.${AWS::Region}.${AWS::URLSuffix}
        - Effect: Allow
          Action:
          - kms:Decrypt
          - kms:GenerateDataKey*
          Resource: !Ref KmsKeyArn
          Condition:
            StringEquals:
              kms:ViaService: !Sub secretsmanager.${AWS::Region}.${AWS::URLSuffix}
            ForAnyValue:ArnLike:
              kms:EncryptionContext:SecretARN: !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*
  SecretsManagerAuthTokenRotation:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      Description: Conducts an AWS Secrets Manager rotation for ElastiCache Replication Group auth token
      CodeUri: ./rotator/
      Handler: rotator.handle
      Timeout: 300
      Policies:
      - VPCAccessPolicy: {}
      - AWSSecretsManagerRotationPolicy:
          FunctionName: !Ref FunctionName
      - Version: 2012-10-17
        Id: RotateAuthToken
        Statement:
          Effect: Allow
          Action:
          - elasticache:DescribeReplicationGroups
          - elasticache:ModifyReplicationGroup
          Resource: !Sub arn:${AWS::Partition}:elasticache:${AWS::Region}:${AWS::AccountId}:replicationgroup:*
      - !If [ KmsKeyArnExists, !Ref SecretDecryptionPolicy, !Ref AWS::NoValue ]
      VpcConfig:
        SubnetIds: !Ref VpcSubnetIds
        SecurityGroupIds: !Ref VpcSecurityGroupIds
      Tags:
        SecretsManagerLambda: Rotation
  SecretsManagerAuthTokenRotationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt SecretsManagerAuthTokenRotation.Arn
      Principal: !Ref InvokingServicePrincipal
  SecretsManagerElastiCacheSecretTargetAttachment:
    Type: AWS::Serverless::Function
    Properties:
      Description: Completes the final link between a Secrets Manager secret and its associated cache cluster
      CodeUri: ./attacher/
      Handler: attacher.handle
      Timeout: 30
      Policies:
      - Version: 2012-10-17
        Id: RetrieveConnectionInformation
        Statement:
        - Effect: Allow
          Action: elasticache:DescribeReplicationGroups
          Resource: !Sub arn:${AWS::Partition}:elasticache:${AWS::Region}:${AWS::AccountId}:replicationgroup:*
        - Effect: Allow
          Action:
          - secretsmanager:GetSecretValue
          - secretsmanager:PutSecretValue
          Resource: !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*
          Condition:
            ForAnyValue:StringEquals:
              secretsmanager:VersionStage: AWSCURRENT
      - !If [ KmsKeyArnExists, !Ref SecretDecryptionPolicy, !Ref AWS::NoValue ]

Outputs:
  RotationLambdaARN:
    Description: The ARN of the rotation Lambda Function
    Value: !GetAtt SecretsManagerAuthTokenRotation.Arn
  AttachmentLambdaARN:
    Description: The ARN of the attachment Lambda Function, to be used as the service token of a CloudFormation custom resource
    Value: !GetAtt SecretsManagerElastiCacheSecretTargetAttachment.Arn
